"""
Hardening content templates.

This module defines canonical, source-of-truth file templates that can be applied
by the updater to keep the project root in a known, auditable state.

You can add more entries to `TEMPLATES` over time as you standardize:
- README.md
- CONTRIBUTING.md
- LICENSE.md
- default __init__.py files
- config examples, etc.
"""

from __future__ import annotations

from typing import Dict


TEMPLATES: Dict[str, str] = {
    "__init__.py": "# Auto-generated by The Veil Updater\n",
    "README.md": (
        "# The Veil\n\n"
        "The Veil is a unified CLI, diagnostics, repair, and updater toolkit.\n"
        "It is designed to be reproducible, auditable, and extensible.\n"
    ),
    "CONTRIBUTING.md": (
        "# Contributing to The Veil\n\n"
        "Thank you for your interest in contributing!\n"
        "- Open issues for bugs and feature requests.\n"
        "- Use pull requests for changes.\n"
        "- Keep changes small and well-documented.\n"
    ),
}


def get_template(name: str) -> str:
    """
    Return the canonical template content for a given filename, if defined.

    Args:
        name: Basename of the file, e.g. 'README.md' or '__init__.py'.

    Returns:
        The template content as a string, or an empty string if not defined.
    """
    return TEMPLATES.get(name, "")
